source 'https://rubygems.org'

gem 'jquery-rails'

gem 'rails', '3.2.1'

group :development do
	gem 'sqlite3'
end

group :production do
	gem 'pg'
	gem 'thin'
end

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end
